# Generated by Django 4.0.5 on 2022-08-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_foodgroups_foods'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foods',
            new_name='Food',
        ),
        migrations.RenameModel(
            old_name='Foodgroups',
            new_name='Foodgroup',
        ),
    ]
