# Generated by Django 4.0.5 on 2022-08-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_rename_foods_food_rename_foodgroups_foodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
