# Generated by Django 4.0.5 on 2022-08-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_alter_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgroup',
            name='group_name',
            field=models.TextField(unique=True),
        ),
    ]
