# Generated by Django 4.0.5 on 2022-08-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_alter_foodgroup_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='group_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.TextField(),
        ),
    ]
