# Generated by Django 4.0.5 on 2022-08-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0007_nutrient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
    ]
