# Generated by Django 4.0.5 on 2022-08-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0008_subgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='subgroup_id',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
