# Generated by Django 4.0.5 on 2022-08-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0009_food_subgroup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='subgroup_id',
            field=models.IntegerField(default=100),
        ),
    ]
