# Generated by Django 4.0.5 on 2022-08-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0010_alter_food_subgroup_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('vf_amt', models.IntegerField()),
                ('protein_amt', models.IntegerField()),
                ('grain_amt', models.IntegerField()),
                ('liquid_amt', models.IntegerField()),
                ('other_amt', models.IntegerField()),
            ],
        ),
    ]
