# Generated by Django 4.0.5 on 2022-08-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_user_id_post_like_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='twit',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
