# Generated by Django 4.0.5 on 2022-08-13 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follower_influencer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='follower',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
