# Generated by Django 4.0.5 on 2022-08-13 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_follower_follow_alter_follower_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='follow',
        ),
    ]
