# Generated by Django 4.0.5 on 2022-08-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_follower_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='person',
        ),
        migrations.AddField(
            model_name='like',
            name='person_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='post_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
