# Generated by Django 4.0.5 on 2022-09-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_comment_question_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
