# Generated by Django 4.0.5 on 2022-06-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bid_id_alter_listing_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_link',
            field=models.CharField(max_length=100),
        ),
    ]
