# Generated by Django 4.0.5 on 2022-06-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
