# Generated by Django 4.0.5 on 2022-06-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_current_bid_watchitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.IntegerField(default=0),
        ),
    ]
