# Generated by Django 4.0.5 on 2022-06-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='owner',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
